### PR TITLE
[zfs-fuse] several fixes for EL5/EL6. gcc flags and some missing files..

### PR DESCRIPTION
**Pull request by ElCoyote27**
Hi Gordan,
Here are the bits that make the rpms build under both EL5 and EL6. It shouldn't change anything for systems above (and including) EL7 as I've created a case statement for every difference.
Please let me know if that's OK for you.
Regards,
Vincent

### CODE REVIEW

**Comment by ElCoyote27** [comment]
Hi Gordan, let me adapt my tree to use these files..
Also, I got rid of the automake bit too as it wasn't portable..
Thank you,
Vincent

**Comment by ElCoyote27** [comment]
Hi Gordan,
I updated my fork a bit.. builds and works fine on EL5/EL6 (both 32bit and 64bit for EL5).
Let me know if that's acceptable for you to merge..
Thanks,
Vincent

**Comment by gordan-bobic** [comment]
Any chance of a minimalized merge request, single unified patch?

**Comment by ElCoyote27** [comment]
Ok, let me re-work my patch..
Thanks,
Vincent

**Pull request closed without merging**
