### PR TITLE
[zfs-fuse] Fix a few things for EL5/EL6

### PR DESCRIPTION
**Pull request by ElCoyote27**
Hi Gordan,
Here's my pull request as a single patch for el5/el6.
Let me know if that's acceptable.
Regards,
Vincent

### CODE REVIEW

**Comment by gordan-bobic** [comment]
How about replacing:
%{__perl} -pi -e 's@-fstrict-volatile-bitfields@@' lib/libumem/Makefile.in
with:
sed -i -e 's/ -fstrict-volatile-bitfields//' lib/libumem/Makefile.in

It means we don't need perl as a build dependency.

Additionally, could the same not be applied to src/SConstruct instead of the modification there?

**Comment by ElCoyote27** [comment]
perl is already an rpm dependency so I think it's a non-issue.
I will change the src/SConstruct stuff to do the same..
Thanks

**Comment by gordan-bobic** [comment]
Thanks. Do you have a revised unified patch?

**Comment by ElCoyote27** [comment]
Nope. Not yet.

**Comment by ElCoyote27** [comment]
Gordan. I had updated this pull request a few days ago. Can you please check?
Commit

**Comment by ElCoyote27** [comment]
I'll be submitting a new pull request wirth a new unified patch shortly.

**Pull request closed without merging**
